package ch.ethz.seb.sps.server.datalayer.batis.model;

import jakarta.annotation.Generated;

public class ScheduledDeleteRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.state")
    private String state;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.start_time")
    private Long startTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.delete_due_time")
    private Long deleteDueTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source Table: scheduled_delete")
    public ScheduledDeleteRecord(Long id, String state, Long startTime, Long deleteDueTime) {
        this.id = id;
        this.state = state;
        this.startTime = startTime;
        this.deleteDueTime = deleteDueTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.state")
    public String getState() {
        return state;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.start_time")
    public Long getStartTime() {
        return startTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2026-02-19T13:37:36.173+01:00", comments="Source field: scheduled_delete.delete_due_time")
    public Long getDeleteDueTime() {
        return deleteDueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete
     *
     * @mbg.generated Thu Feb 19 13:37:36 CET 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", state=").append(state);
        sb.append(", startTime=").append(startTime);
        sb.append(", deleteDueTime=").append(deleteDueTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete
     *
     * @mbg.generated Thu Feb 19 13:37:36 CET 2026
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduledDeleteRecord other = (ScheduledDeleteRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getDeleteDueTime() == null ? other.getDeleteDueTime() == null : this.getDeleteDueTime().equals(other.getDeleteDueTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduled_delete
     *
     * @mbg.generated Thu Feb 19 13:37:36 CET 2026
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getDeleteDueTime() == null) ? 0 : getDeleteDueTime().hashCode());
        return result;
    }
}