package ch.ethz.seb.sps.server.datalayer.batis.model;

import jakarta.annotation.Generated;

public class ScreenshotDataLiveCacheRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source field: screenshot_data_live_cache.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source field: screenshot_data_live_cache.session_uuid")
    private String sessionUuid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source field: screenshot_data_live_cache.id_latest_ssd")
    private Long idLatestSsd;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source Table: screenshot_data_live_cache")
    public ScreenshotDataLiveCacheRecord(Long id, String sessionUuid, Long idLatestSsd) {
        this.id = id;
        this.sessionUuid = sessionUuid;
        this.idLatestSsd = idLatestSsd;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source field: screenshot_data_live_cache.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source field: screenshot_data_live_cache.session_uuid")
    public String getSessionUuid() {
        return sessionUuid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2025-08-26T16:02:14.757+02:00", comments="Source field: screenshot_data_live_cache.id_latest_ssd")
    public Long getIdLatestSsd() {
        return idLatestSsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screenshot_data_live_cache
     *
     * @mbg.generated Tue Aug 26 16:02:14 CEST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sessionUuid=").append(sessionUuid);
        sb.append(", idLatestSsd=").append(idLatestSsd);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screenshot_data_live_cache
     *
     * @mbg.generated Tue Aug 26 16:02:14 CEST 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScreenshotDataLiveCacheRecord other = (ScreenshotDataLiveCacheRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSessionUuid() == null ? other.getSessionUuid() == null : this.getSessionUuid().equals(other.getSessionUuid()))
            && (this.getIdLatestSsd() == null ? other.getIdLatestSsd() == null : this.getIdLatestSsd().equals(other.getIdLatestSsd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screenshot_data_live_cache
     *
     * @mbg.generated Tue Aug 26 16:02:14 CEST 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSessionUuid() == null) ? 0 : getSessionUuid().hashCode());
        result = prime * result + ((getIdLatestSsd() == null) ? 0 : getIdLatestSsd().hashCode());
        return result;
    }
}