package ch.ethz.seb.sps.server.datalayer.batis.model;

import javax.annotation.Generated;

public class WebserviceInfoRecord {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.uuid")
    private String uuid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.server_address")
    private String serverAddress;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.master")
    private Integer master;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.creation_time")
    private Long creationTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.last_update_time")
    private Long lastUpdateTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.892+02:00", comments="Source field: webservice_server_info.termination_time")
    private Long terminationTime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source Table: webservice_server_info")
    public WebserviceInfoRecord(Long id, String uuid, String serverAddress, Integer master, Long creationTime, Long lastUpdateTime, Long terminationTime) {
        this.id = id;
        this.uuid = uuid;
        this.serverAddress = serverAddress;
        this.master = master;
        this.creationTime = creationTime;
        this.lastUpdateTime = lastUpdateTime;
        this.terminationTime = terminationTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.uuid")
    public String getUuid() {
        return uuid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.server_address")
    public String getServerAddress() {
        return serverAddress;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.master")
    public Integer getMaster() {
        return master;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.891+02:00", comments="Source field: webservice_server_info.creation_time")
    public Long getCreationTime() {
        return creationTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.892+02:00", comments="Source field: webservice_server_info.last_update_time")
    public Long getLastUpdateTime() {
        return lastUpdateTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2023-08-15T14:43:27.892+02:00", comments="Source field: webservice_server_info.termination_time")
    public Long getTerminationTime() {
        return terminationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webservice_server_info
     *
     * @mbg.generated Tue Aug 15 14:43:27 CEST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uuid=").append(uuid);
        sb.append(", serverAddress=").append(serverAddress);
        sb.append(", master=").append(master);
        sb.append(", creationTime=").append(creationTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", terminationTime=").append(terminationTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webservice_server_info
     *
     * @mbg.generated Tue Aug 15 14:43:27 CEST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WebserviceInfoRecord other = (WebserviceInfoRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getServerAddress() == null ? other.getServerAddress() == null : this.getServerAddress().equals(other.getServerAddress()))
            && (this.getMaster() == null ? other.getMaster() == null : this.getMaster().equals(other.getMaster()))
            && (this.getCreationTime() == null ? other.getCreationTime() == null : this.getCreationTime().equals(other.getCreationTime()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getTerminationTime() == null ? other.getTerminationTime() == null : this.getTerminationTime().equals(other.getTerminationTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webservice_server_info
     *
     * @mbg.generated Tue Aug 15 14:43:27 CEST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getServerAddress() == null) ? 0 : getServerAddress().hashCode());
        result = prime * result + ((getMaster() == null) ? 0 : getMaster().hashCode());
        result = prime * result + ((getCreationTime() == null) ? 0 : getCreationTime().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getTerminationTime() == null) ? 0 : getTerminationTime().hashCode());
        return result;
    }
}