package ch.ethz.seb.sps.domain;

import jakarta.annotation.Generated;

/** Defines the global names of the domain model and domain model fields.
* This shall be used as a static overall domain model names reference within SEB Server Web-Service as well as within the integrated GUI
* This file is generated by the ch.ethz.seb.sps.generator.DomainModelNameReferencePlugin and must not be edited manually.**/
@Generated(value="org.mybatis.generator.api.MyBatisGenerator",comments="ch.ethz.seb.sps.generator.DomainModelNameReferencePlugin",date="2025-08-26T16:02:14.699+02:00")
public interface Domain {

    interface USER {
        String TYPE_NAME = "User";
        String REFERENCE_NAME = "users";
        String ATTR_ID = "id";
        String ATTR_UUID = "uuid";
        String ATTR_NAME = "name";
        String ATTR_SURNAME = "surname";
        String ATTR_USERNAME = "username";
        String ATTR_PASSWORD = "password";
        String ATTR_EMAIL = "email";
        String ATTR_LANGUAGE = "language";
        String ATTR_TIMEZONE = "timezone";
        String ATTR_ROLES = "roles";
        String ATTR_CREATION_TIME = "creationTime";
        String ATTR_LAST_UPDATE_TIME = "lastUpdateTime";
        String ATTR_TERMINATION_TIME = "terminationTime";
    }

    interface CLIENT_ACCESS {
        String TYPE_NAME = "ClientAccess";
        String REFERENCE_NAME = "clientAccesss";
        String ATTR_ID = "id";
        String ATTR_UUID = "uuid";
        String ATTR_NAME = "name";
        String ATTR_DESCRIPTION = "description";
        String ATTR_CLIENT_NAME = "clientName";
        String ATTR_CLIENT_SECRET = "clientSecret";
        String ATTR_OWNER = "owner";
        String ATTR_CREATION_TIME = "creationTime";
        String ATTR_LAST_UPDATE_TIME = "lastUpdateTime";
        String ATTR_TERMINATION_TIME = "terminationTime";
    }

    interface EXAM {
        String TYPE_NAME = "Exam";
        String REFERENCE_NAME = "exams";
        String ATTR_ID = "id";
        String ATTR_UUID = "uuid";
        String ATTR_NAME = "name";
        String ATTR_DESCRIPTION = "description";
        String ATTR_URL = "url";
        String ATTR_TYPE = "type";
        String ATTR_OWNER = "owner";
        String ATTR_SUPPORTER = "supporter";
        String ATTR_CREATION_TIME = "creationTime";
        String ATTR_LAST_UPDATE_TIME = "lastUpdateTime";
        String ATTR_TERMINATION_TIME = "terminationTime";
        String ATTR_START_TIME = "startTime";
        String ATTR_END_TIME = "endTime";
        String ATTR_DELETION_TIME = "deletionTime";
    }

    interface SEB_GROUP {
        String TYPE_NAME = "SebGroup";
        String REFERENCE_NAME = "sebGroups";
        String ATTR_ID = "id";
        String ATTR_UUID = "uuid";
        String ATTR_NAME = "name";
        String ATTR_DESCRIPTION = "description";
        String ATTR_OWNER = "owner";
        String ATTR_CREATION_TIME = "creationTime";
        String ATTR_LAST_UPDATE_TIME = "lastUpdateTime";
        String ATTR_TERMINATION_TIME = "terminationTime";
        String ATTR_EXAM_ID = "examId";
    }

    interface SESSION {
        String TYPE_NAME = "Session";
        String REFERENCE_NAME = "sessions";
        String ATTR_ID = "id";
        String ATTR_GROUP_ID = "groupId";
        String ATTR_UUID = "uuid";
        String ATTR_IMAGE_FORMAT = "imageFormat";
        String ATTR_CLIENT_NAME = "clientName";
        String ATTR_CLIENT_IP = "clientIp";
        String ATTR_CLIENT_MACHINE_NAME = "clientMachineName";
        String ATTR_CLIENT_OS_NAME = "clientOsName";
        String ATTR_CLIENT_VERSION = "clientVersion";
        String ATTR_CREATION_TIME = "creationTime";
        String ATTR_LAST_UPDATE_TIME = "lastUpdateTime";
        String ATTR_TERMINATION_TIME = "terminationTime";
        String ATTR_ENCRYPTION_KEY = "encryptionKey";
    }

    interface SCREENSHOT_DATA {
        String TYPE_NAME = "ScreenshotData";
        String REFERENCE_NAME = "screenshotDatas";
        String ATTR_ID = "id";
        String ATTR_SESSION_UUID = "sessionUuid";
        String ATTR_TIMESTAMP = "timestamp";
        String ATTR_IMAGE_FORMAT = "imageFormat";
        String ATTR_META_DATA = "metaData";
    }

    interface SCREENSHOT_DATA_LIVE_CACHE {
        String TYPE_NAME = "ScreenshotDataLiveCache";
        String REFERENCE_NAME = "screenshotDataLiveCaches";
        String ATTR_ID = "id";
        String ATTR_SESSION_UUID = "sessionUuid";
        String ATTR_ID_LATEST_SSD = "idLatestSsd";
    }

    interface SCREENSHOT {
        String TYPE_NAME = "Screenshot";
        String REFERENCE_NAME = "screenshots";
        String ATTR_ID = "id";
        String ATTR_IMAGE = "image";
    }

    interface ENTITY_PRIVILEGE {
        String TYPE_NAME = "EntityPrivilege";
        String REFERENCE_NAME = "entityPrivileges";
        String ATTR_ID = "id";
        String ATTR_ENTITY_TYPE = "entityType";
        String ATTR_ENTITY_ID = "entityId";
        String ATTR_USER_UUID = "userUuid";
        String ATTR_PRIVILEGES = "privileges";
    }

    interface ADDITIONAL_ATTRIBUTE {
        String TYPE_NAME = "AdditionalAttribute";
        String REFERENCE_NAME = "additionalAttributes";
        String ATTR_ID = "id";
        String ATTR_ENTITY_TYPE = "entityType";
        String ATTR_ENTITY_ID = "entityId";
        String ATTR_NAME = "name";
        String ATTR_VALUE = "value";
    }

    interface WEBSERVICE_SERVER_INFO {
        String TYPE_NAME = "WebserviceServerInfo";
        String REFERENCE_NAME = "webserviceServerInfos";
        String ATTR_ID = "id";
        String ATTR_UUID = "uuid";
        String ATTR_SERVER_ADDRESS = "serverAddress";
        String ATTR_MASTER = "master";
        String ATTR_CREATION_TIME = "creationTime";
        String ATTR_LAST_UPDATE_TIME = "lastUpdateTime";
        String ATTR_TERMINATION_TIME = "terminationTime";
    }

    interface AUDIT_LOG {
        String TYPE_NAME = "AuditLog";
        String REFERENCE_NAME = "auditLogs";
        String ATTR_ID = "id";
        String ATTR_USER_UUID = "userUuid";
        String ATTR_TIMESTAMP = "timestamp";
        String ATTR_ACTIVITY_TYPE = "activityType";
        String ATTR_ENTITY_TYPE = "entityType";
        String ATTR_ENTITY_ID = "entityId";
        String ATTR_MESSAGE = "message";
    }
}