# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [master]

jobs:
  maven-build-test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4.1.1
    -
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '17'
        distribution: 'adopt'
    -
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    -
      name: Build with Maven
      run: mvn clean install

  maven-build-docker:
    needs: maven-build-test
    # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    -
      name: Get short SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
    -
      name: Store short SHA as environment variable
      run: echo $SHA >> $env:GITHUB_OUTPUT
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    -
      name: Set env
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    -
      name: Test tag name
      run: |
        echo $TAG_NAME
        echo ${{ env.TAG_NAME }}
    -
      name: Checkout repository
      uses: actions/checkout@v4.1.1
    -
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '17'
        distribution: 'adopt'
    -
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    -
      name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true -Dseb-sps-version="${{ env.TAG_NAME }}-${{ env.SHA }}" 
      env: 
         seb-sps-version: ${{ env.TAG_NAME }}-${{ env.SHA }}
    -
      name: Simplify package name
      run: mv target/seb-screen-proctoring-service-${{ env.TAG_NAME }}-${{ env.SHA }}.jar target/seb-sps.jar
    -
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Package
        path: target/seb-sps.jar

  docker-build:
    needs: maven-build-docker
    # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $TAG_NAME
        echo ${{ env.TAG_NAME }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.1.0
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Download a single artifact
      uses: actions/download-artifact@v4.1.4
      with:
          name: Package
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          anhefti/seb-sps:${{ env.TAG_NAME }}
          
  docker-build-admin:
    needs: maven-build-docker
    # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $TAG_NAME
          echo ${{ env.TAG_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_ADMIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ADMIN_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Download a single artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: Package
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            sebadmin/seb-sps:${{ env.TAG_NAME }}
          
  cleanup:
    needs: docker-build
     # Run only on tagging
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    -
      name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v4.1.0
      with:
          name: Package
